import Head from 'next/head';

export default function Blog() {
  return (
    <div className="bg-slate-100 dark:bg-slate-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FOLDER}/favicon.ico`}
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-coy-without-shadows.min.css"
          rel="stylesheet"
        />
      </Head>
      <div className="py-40 max-w-5xl mx-auto">
        <h1 className="text-6xl text-center font-extrabold text-slate-900 dark:text-slate-100">
          A tour of the new features in the Typography plugin v0.5
        </h1>

        <article className="mt-16 mx-auto prose prose-cyan prose-slate dark:prose-invert">
          <a>Hello there</a>
          <p>
            For years parents have espoused the health benefits of eating garlic
            bread with cheese to their children, with the food earning such an
            iconic status in our culture that kids will often dress up as warm,
            cheesy loaf for Halloween.
          </p>
          <p>
            But a recent study shows that the celebrated appetizer may be linked
            to a series of rabies cases springing up around the country.
          </p>
          <blockquote>Hello world</blockquote>
          <h1>
            An ea, quae per vinitorem antea consequebatur, per se ipsa curabit?
          </h1>

          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bonum negas
            esse divitias, praeposìtum esse dicis? Sequitur disserendi ratio
            cognitioque naturae; <b>Sed quae tandem ista ratio est?</b>
            <b>In schola desinis.</b>
          </p>

          <ul>
            <li>Respondent extrema primis, media utrisque, omnia omnibus.</li>
            <li>Sed ad haec, nisi molestum est, habeo quae velim.</li>
            <li>Tubulo putas dicere?</li>
            <li>
              An potest, inquit ille, quicquam esse suavius quam nihil dolere?
            </li>
            <li>
              Tu autem negas fortem esse quemquam posse, qui dolorem malum
              putet.
            </li>
          </ul>

          <blockquote cite="http://loripsum.net">
            Idque quo magis quidam ita faciunt, ut iure etiam reprehendantur,
            hoc magis intellegendum est haec ipsa nimia in quibusdam futura non
            fuisse, nisi quaedam essent modica natura.
          </blockquote>

          <p>
            Etenim semper illud extra est, quod arte comprehenditur. Tollitur
            beneficium, tollitur gratia, quae sunt vincla concordiae. Duo Reges:
            constructio interrete.
          </p>

          <ol>
            <li>
              Quid tanto concursu honestissimorum studiorum, tanto virtutum
              comitatu, si ea nullam ad aliam rem nisi ad voluptatem
              conquiruntur?
            </li>
            <li>
              Hinc ceteri particulas arripere conati suam quisque videro voluit
              afferre sententiam.
            </li>
            <li>Tum Torquatus: Prorsus, inquit, assentior;</li>
          </ol>

          <pre>
            <code>print(hello world)</code>
          </pre>

          <p>
            <b> HTML </b> stands for
            <i>
              <u> Hyper Text Markup Language. </u>
            </i>
            It is used to create a web pages and applications. This language is
            easily understandable by the user and also be modifiable. It is
            actually a Markup language, hence it provides a flexible way for
            designing the web pages along with the text.
          </p>
          <p>
            HTML file is made up of different elements. <b> An element </b> is a
            collection of
            <i> start tag, end tag, attributes and the text between them</i>.
          </p>
        </article>
      </div>
    </div>
  );
}
