import Head from 'next/head';

export default function Home() {
  return (
    <div className="bg-slate-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-bold text-slate-700">Hello World</div>
    </div>
  );
}
